# Import Libaries

In [73]:
import numpy as np
import pandas as pd
import warnings

# Importing Data

In [74]:
crop = pd.read_csv("Crop_recommendation.csv")
crop.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

# Asq Six Question to yourself

In [75]:
crop.shape

(2200, 8)

In [76]:
crop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [77]:
crop.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [78]:
crop.duplicated().sum()

np.int64(0)

In [79]:
crop.describe()

,N,P,K,temperature,humidity,ph,rainfall
count,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000,2200.000000
mean,50.551818,53.362727,48.149091,25.616244,71.481779,6.469480,103.463655
std,36.917334,32.985883,50.647931,5.063749,22.263812,0.773938,54.958389
min,0.000000,5.000000,5.000000,8.825675,14.258040,3.504752,20.211267
25%,21.000000,28.000000,20.000000,22.769375,60.261953,5.971693,64.551686
50%,37.000000,51.000000,32.000000,25.598693,80.473146,6.425045,94.867624
75%,84.250000,68.000000,49.000000,28.561654,89.948771,6.923643,124.267508
max,140.000000,145.000000,205.000000,43.675493,99.981876,9.935091,298.560117

In [80]:
crop['label'].value_counts()

label
rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: count, dtype: int64

# Encoding

In [81]:
crop_dict = {
    'rice': 1,
    'maize': 2,
    'jute': 3,
    'cotton': 4,
    'coconut': 5,
    'papaya': 6,
    'orange': 7,
    'apple': 8,
    'muskmelon': 9,
    'watermelon': 10,
    'grapes': 11,
    'mango': 12,
    'banana': 13,
    'pomegranate': 14,
    'lentil': 15,
    'blackgram': 16,
    'mungbean': 17,
    'mothbeans': 18,
    'pigeonpeas': 19,
    'kidneybeans': 20,
    'chickpea': 21,
    'coffee': 22
}
crop['crop_num']=  crop['label'].map(crop_dict)

In [82]:
crop

,N,P,K,temperature,humidity,ph,rainfall,label,crop_num
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice,1
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice,1
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice,1
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice,1
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice,1
...,...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,coffee,22
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,coffee,22
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,coffee,22
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,coffee,22
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,coffee,22

In [83]:
crop.drop(['label'],axis=1,inplace=True)
crop.head()

    N   P   K  temperature   humidity        ph    rainfall  crop_num
0  90  42  43    20.879744  82.002744  6.502985  202.935536         1
1  85  58  41    21.770462  80.319644  7.038096  226.655537         1
2  60  55  44    23.004459  82.320763  7.840207  263.964248         1
3  74  35  40    26.491096  80.158363  6.980401  242.864034         1
4  78  42  42    20.130175  81.604873  7.628473  262.717340         1

# Train Test Split

In [84]:
X = crop.drop(['crop_num'],axis=1)
y = crop['crop_num']

In [85]:
X

        N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

In [86]:
y

0        1
1        1
2        1
3        1
4        1
        ..
2195    22
2196    22
2197    22
2198    22
2199    22
Name: crop_num, Length: 2200, dtype: int64

In [87]:
y.shape

(2200,)

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [90]:
X_train

        N    P    K  temperature   humidity        ph    rainfall
1656   17   16   14    16.396243  92.181519  6.625539  102.944161
752    37   79   19    27.543848  69.347863  7.143943   69.408782
892     7   73   25    27.521856  63.132153  7.288057   45.208411
1041  101   70   48    25.360592  75.031933  6.012697  116.553145
1179    0   17   30    35.474783  47.972305  6.279134   97.790725
...   ...  ...  ...          ...        ...       ...         ...
1638   10    5    5    21.213070  91.353492  7.817846  112.983436
1095  108   94   47    27.359116  84.546250  6.387431   90.812505
1130   11   36   31    27.920633  51.779659  6.475449  100.258567
1294   11  124  204    13.429886  80.066340  6.361141   71.400430
860    32   78   22    23.970814  62.355576  7.007038   53.409060

[1760 rows x 7 columns]


# Scale the features using MinMaxScaler

In [91]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()

X_train = ms.fit_transform(X_train)
X_test = ms.transform(X_test)

In [92]:
X_train

array([[0.12142857, 0.07857143, 0.045     , ..., 0.9089898 , 0.48532225,
        0.29685161],
       [0.26428571, 0.52857143, 0.07      , ..., 0.64257946, 0.56594073,
        0.17630752],
       [0.05      , 0.48571429, 0.1       , ..., 0.57005802, 0.58835229,
        0.08931844],
       ...,
       [0.07857143, 0.22142857, 0.13      , ..., 0.43760347, 0.46198144,
        0.28719815],
       [0.07857143, 0.85      , 0.995     , ..., 0.76763665, 0.44420505,
        0.18346657],
       [0.22857143, 0.52142857, 0.085     , ..., 0.56099735, 0.54465022,
        0.11879596]], shape=(1760, 7))

# Training Models

In [93]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, ExtraTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, GradientBoostingClassifier, AdaBoostClassifier
# Define all models
models = {
    'Logistic Regression': LogisticRegression(),
    'Naive Bayes': GaussianNB(),
    'Support Vector Machine': SVC(probability=True),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Decision Tree': DecisionTreeClassifier(),
    'Random Forest': RandomForestClassifier(),
    'Bagging': BaggingClassifier(),
    'AdaBoost': AdaBoostClassifier(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Extra Trees': ExtraTreeClassifier(),
}
warnings.filterwarnings("ignore", category=FutureWarning, message=".*algorithm.*")


# Step 1: Split Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Feature Scaling
# Combine StandardScaler and MinMaxScaler for consistency
standard_scaler = StandardScaler()
minmax_scaler = MinMaxScaler()

X_train_scaled = standard_scaler.fit_transform(minmax_scaler.fit_transform(X_train))
X_test_scaled = standard_scaler.transform(minmax_scaler.transform(X_test))

# Adjust AdaBoost algorithm to SAMME
models['AdaBoost'] = AdaBoostClassifier(algorithm='SAMME')

# Train and evaluate models
for name, model in models.items():
    print(f"Training {name}...")
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    
    # Evaluate performance
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {accuracy:.2f}")
    
    # Avoid undefined precision warnings
    report = classification_report(y_test, y_pred, zero_division=0)
    print("Classification Report:")
    print(report)
    print("==========================================================")

Training Logistic Regression...
Logistic Regression Accuracy: 0.96
Classification Report:
              precision    recall  f1-score   support

           1       0.88      0.79      0.83        19
           2       1.00      0.95      0.98        21
           3       0.83      0.87      0.85        23
           4       0.94      1.00      0.97        17
           5       1.00      1.00      1.00        27
           6       0.96      0.96      0.96        23
           7       1.00      1.00      1.00        14
           8       1.00      1.00      1.00        23
           9       1.00      1.00      1.00        17
          10       1.00      1.00      1.00        19
          11       1.00      1.00      1.00        14
          12       1.00      1.00      1.00        19
          13       1.00      1.00      1.00        21
          14       1.00      1.00      1.00        23
          15       0.85      1.00      0.92        11
          16       0.90      0.95      0.93        20
          17       1.00      1.00      1.00        19
          18       1.00      0.92      0.96        24
          19       0.91      0.87      0.89        23
          20       0.95      0.95      0.95        20
          21       1.00      1.00      1.00        26
          22       0.94      1.00      0.97        17

    accuracy                           0.96       440
   macro avg       0.96      0.97      0.96       440
weighted avg       0.96      0.96      0.96       440

==========================================================
Training Naive Bayes...
Naive Bayes Accuracy: 1.00
Classification Report:
              precision    recall  f1-score   support

           1       1.00      0.89      0.94        19
           2       1.00      1.00      1.00        21
           3       0.92      1.00      0.96        23
           4       1.00      1.00      1.00        17
           5       1.00      1.00      1.00        27
           6       1.00      1.00      1.00        23
           7       1.00      1.00      1.00        14
           8       1.00      1.00      1.00        23
           9       1.00      1.00      1.00        17
          10       1.00      1.00      1.00        19
          11       1.00      1.00      1.00        14
          12       1.00      1.00      1.00        19
          13       1.00      1.00      1.00        21
          14       1.00      1.00      1.00        23
          15       1.00      1.00      1.00        11
          16       1.00      1.00      1.00        20
          17       1.00      1.00      1.00        19
          18       1.00      1.00      1.00        24
          19       1.00      1.00      1.00        23
          20       1.00      1.00      1.00        20
          21       1.00      1.00      1.00        26
          22       1.00      1.00      1.00        17

    accuracy                           1.00       440
   macro avg       1.00      1.00      1.00       440
weighted avg       1.00      1.00      1.00       440

==========================================================
Training Support Vector Machine...
Support Vector Machine Accuracy: 0.97
Classification Report:
              precision    recall  f1-score   support

           1       0.93      0.68      0.79        19
           2       1.00      0.95      0.98        21
           3       0.78      0.91      0.84        23
           4       0.94      1.00      0.97        17
           5       1.00      1.00      1.00        27
           6       1.00      1.00      1.00        23
           7       1.00      1.00      1.00        14
           8       1.00      1.00      1.00        23
           9       1.00      1.00      1.00        17
          10       1.00      1.00      1.00        19
          11       1.00      1.00      1.00        14
          12       1.00      1.00      1.00        19
          13       1.00      1.00      1.00        21
          14       1.00      1.00      1.00        23
          15       0.79      1.00      0.88        11
          16       1.00      0.95      0.97        20
          17       1.00      1.00      1.00        19
          18       1.00      0.92      0.96        24
          19       1.00      0.91      0.95        23
          20       0.91      1.00      0.95        20
          21       1.00      1.00      1.00        26
          22       0.94      1.00      0.97        17

    accuracy                           0.97       440
   macro avg       0.97      0.97      0.97       440
weighted avg       0.97      0.97      0.97       440

==========================================================
Training K-Nearest Neighbors...
K-Nearest Neighbors Accuracy: 0.96
Classification Report:
              precision    recall  f1-score   support

           1       0.93      0.74      0.82        19
           2       1.00      0.90      0.95        21
           3       0.82      1.00      0.90        23
           4       0.89      1.00      0.94        17
           5       1.00      1.00      1.00        27
           6       1.00      0.96      0.98        23
           7       1.00      1.00      1.00        14
           8       1.00      1.00      1.00        23
           9       1.00      1.00      1.00        17
          10       1.00      1.00      1.00        19
          11       1.00      1.00      1.00        14
          12       0.90      1.00      0.95        19
          13       1.00      1.00      1.00        21
          14       1.00      1.00      1.00        23
          15       0.69      1.00      0.81        11
          16       0.95      0.95      0.95        20
          17       1.00      1.00      1.00        19
          18       1.00      0.83      0.91        24
          19       1.00      0.78      0.88        23
          20       0.91      1.00      0.95        20
          21       1.00      1.00      1.00        26
          22       1.00      1.00      1.00        17

    accuracy                           0.96       440
   macro avg       0.96      0.96      0.96       440
weighted avg       0.97      0.96      0.96       440

==========================================================
Training Decision Tree...
Decision Tree Accuracy: 0.98
Classification Report:
              precision    recall  f1-score   support

           1       0.85      0.89      0.87        19
           2       1.00      1.00      1.00        21
           3       0.91      0.87      0.89        23
           4       1.00      1.00      1.00        17
           5       1.00      1.00      1.00        27
           6       1.00      1.00      1.00        23
           7       1.00      1.00      1.00        14
           8       1.00      1.00      1.00        23
           9       1.00      1.00      1.00        17
          10       1.00      1.00      1.00        19
          11       1.00      1.00      1.00        14
          12       1.00      1.00      1.00        19
          13       1.00      1.00      1.00        21
          14       1.00      1.00      1.00        23
          15       0.92      1.00      0.96        11
          16       0.95      1.00      0.98        20
          17       1.00      1.00      1.00        19
          18       1.00      0.92      0.96        24
          19       1.00      1.00      1.00        23
          20       1.00      1.00      1.00        20
          21       1.00      1.00      1.00        26
          22       1.00      1.00      1.00        17

    accuracy                           0.98       440
   macro avg       0.98      0.99      0.98       440
weighted avg       0.98      0.98      0.98       440

==========================================================
Training Random Forest...
Random Forest Accuracy: 0.99
Classification Report:
              precision    recall  f1-score   support

           1       1.00      0.89      0.94        19
           2       1.00      1.00      1.00        21
           3       0.92      1.00      0.96        23
           4       1.00      1.00      1.00        17
           5       1.00      1.00      1.00        27
           6       1.00      1.00      1.00        23
           7       1.00      1.00      1.00        14
           8       1.00      1.00      1.00        23
           9       1.00      1.00      1.00        17
          10       1.00      1.00      1.00        19
          11       1.00      1.00      1.00        14
          12       1.00      1.00      1.00        19
          13       1.00      1.00      1.00        21
          14       1.00      1.00      1.00        23
          15       0.92      1.00      0.96        11
          16       1.00      1.00      1.00        20
          17       1.00      1.00      1.00        19
          18       1.00      0.96      0.98        24
          19       1.00      1.00      1.00        23
          20       1.00      1.00      1.00        20
          21       1.00      1.00      1.00        26
          22       1.00      1.00      1.00        17

    accuracy                           0.99       440
   macro avg       0.99      0.99      0.99       440
weighted avg       0.99      0.99      0.99       440

==========================================================
Training Bagging...
Bagging Accuracy: 0.99
Classification Report:
              precision    recall  f1-score   support

           1       0.94      0.89      0.92        19
           2       1.00      1.00      1.00        21
           3       0.92      0.96      0.94        23
           4       1.00      1.00      1.00        17
           5       1.00      1.00      1.00        27
           6       1.00      1.00      1.00        23
           7       1.00      1.00      1.00        14
           8       1.00      1.00      1.00        23
           9       1.00      1.00      1.00        17
          10       1.00      1.00      1.00        19
          11       1.00      1.00      1.00        14
          12       1.00      1.00      1.00        19
          13       1.00      1.00      1.00        21
          14       1.00      1.00      1.00        23
          15       0.92      1.00      0.96        11
          16       1.00      1.00      1.00        20
          17       1.00      1.00      1.00        19
          18       1.00      0.96      0.98        24
          19       1.00      1.00      1.00        23
          20       1.00      1.00      1.00        20
          21       1.00      1.00      1.00        26
          22       1.00      1.00      1.00        17

    accuracy                           0.99       440
   macro avg       0.99      0.99      0.99       440
weighted avg       0.99      0.99      0.99       440

==========================================================
Training AdaBoost...
AdaBoost Accuracy: 0.15
Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00        19
           2       0.00      0.00      0.00        21
           3       0.00      0.00      0.00        23
           4       0.00      0.00      0.00        17
           5       0.00      0.00      0.00        27
           6       0.00      0.00      0.00        23
           7       0.00      0.00      0.00        14
           8       0.00      0.00      0.00        23
           9       0.00      0.00      0.00        17
          10       0.23      1.00      0.37        19
          11       0.00      0.00      0.00        14
          12       0.06      1.00      0.11        19
          13       0.00      0.00      0.00        21
          14       0.00      0.00      0.00        23
          15       0.00      0.00      0.00        11
          16       0.00      0.00      0.00        20
          17       0.00      0.00      0.00        19
          18       0.00      0.00      0.00        24
          19       0.00      0.00      0.00        23
          20       0.00      0.00      0.00        20
          21       0.87      1.00      0.93        26
          22       0.00      0.00      0.00        17

    accuracy                           0.15       440
   macro avg       0.05      0.14      0.06       440
weighted avg       0.06      0.15      0.08       440

==========================================================
Training Gradient Boosting...
Gradient Boosting Accuracy: 0.98
Classification Report:
              precision    recall  f1-score   support

           1       1.00      0.79      0.88        19
           2       1.00      0.95      0.98        21
           3       0.82      1.00      0.90        23
           4       0.94      1.00      0.97        17
           5       1.00      0.96      0.98        27
           6       1.00      1.00      1.00        23
           7       1.00      1.00      1.00        14
           8       1.00      1.00      1.00        23
           9       1.00      1.00      1.00        17
          10       1.00      1.00      1.00        19
          11       1.00      1.00      1.00        14
          12       1.00      1.00      1.00        19
          13       1.00      1.00      1.00        21
          14       1.00      1.00      1.00        23
          15       0.92      1.00      0.96        11
          16       0.95      1.00      0.98        20
          17       1.00      1.00      1.00        19
          18       1.00      0.96      0.98        24
          19       1.00      0.96      0.98        23
          20       1.00      1.00      1.00        20
          21       1.00      1.00      1.00        26
          22       1.00      1.00      1.00        17

    accuracy                           0.98       440
   macro avg       0.98      0.98      0.98       440
weighted avg       0.98      0.98      0.98       440

==========================================================
Training Extra Trees...
Extra Trees Accuracy: 0.91
Classification Report:
              precision    recall  f1-score   support

           1       0.93      0.74      0.82        19
           2       0.91      0.95      0.93        21
           3       0.81      0.96      0.88        23
           4       1.00      0.88      0.94        17
           5       0.96      0.96      0.96        27
           6       0.80      0.87      0.83        23
           7       0.93      0.93      0.93        14
           8       1.00      1.00      1.00        23
           9       1.00      1.00      1.00        17
          10       1.00      1.00      1.00        19
          11       1.00      1.00      1.00        14
          12       1.00      0.95      0.97        19
          13       1.00      0.90      0.95        21
          14       0.96      1.00      0.98        23
          15       0.53      0.91      0.67        11
          16       0.80      0.80      0.80        20
          17       0.85      0.89      0.87        19
          18       0.95      0.83      0.89        24
          19       0.94      0.74      0.83        23
          20       0.90      0.95      0.93        20
          21       0.92      0.92      0.92        26
          22       1.00      0.94      0.97        17

    accuracy                           0.91       440
   macro avg       0.92      0.92      0.91       440
weighted avg       0.92      0.91      0.92       440

==========================================================

In [94]:
# finally selected randomforest model

rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
ypred = rfc.predict(X_test)
accuracy_score(y_test,ypred)

0.9931818181818182

In [95]:
# or gausianjb
gnb = GaussianNB()
gnb.fit(X_train,y_train)
ypred = gnb.predict(X_test)
accuracy_score(y_test,ypred)

0.9954545454545455

# Predictive System

In [96]:
import pickle
pickle.dump(rfc,open('model.pkl','wb'))
pickle.dump(ms,open('minmaxscaler.pkl','wb'))